# Generated by Django 5.1.4 on 2024-12-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='início')),
                ('funcionarios', models.ManyToManyField(to='core.funcionario')),
            ],
        ),
    ]
