# Generated by Django 5.1.2 on 2024-11-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('tipo_objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objetos.tipo_objeto')),
            ],
        ),
    ]
